name: Update Sitemap

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Generate sitemap
        run: python sitemap_gen.py  # Replace with your script name

      - name: Commit and push sitemap
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions[bot]"
          git add sitemap.xml
          git commit -m "Update sitemap.xml"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
